### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [vjek/log_gen_demo#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by vjek** [comment]
Whichever one is the most free, most public, and without any ownership or copyright.

In other words, feel free to copy it, modify it, use it for whatever you want.  If you can copy it, turn it into a product, and make a million dollars, by all means, do so. :-)

**Comment by suprafun** [comment]
Sorry for my late reply. Thank you so very much for your kindness : )
